[build-system]
requires = ["setuptools>=68", "pybind11", "numpy>=2.0.0"]

[project]
name = "minimd"
version = "0.4.0"
requires-python = ">=3.10"
dependencies = ["numpy>=2.0.0", "pyyaml", "ninja", "pybind11", "matplotlib"]

[project.scripts]
minimd = "minimd.__main__:main"
